name: Deploy Docker

on:
  #  push:
  #    branches: [ "main" ]
   workflow_dispatch:
jobs:
  sonarcloud-dockerfile-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker File Code
        uses: actions/checkout@v4
  deploy:
    needs: sonarcloud-dockerfile-check

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t akashs2002/test-actions
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - run: docker push akashs2002/test-actions:latest
