name: deploy-Dist-actions
on: [push,workflow_dispatch]
jobs:
    test:
       runs-on: ubuntu-latest
       steps:
           - name: Get code 
             run:  |
               echo "hello world!"
